<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="otywin-17" name="com.formsdirectinc.functionaltests.apps.TestEngine" tests="1" failures="0" timestamp="24 Aug 2016 12:14:06 GMT" time="116.758" errors="1">
  <testcase name="start" time="116.758" classname="com.formsdirectinc.functionaltests.apps.TestEngine">
    <error type="java.io.FileNotFoundException" message="C:\DCIS\14-06\src\test\resources\prepurchaceOutput\paymentsuccess.txt (The system cannot find the file specified)">
      <![CDATA[java.io.FileNotFoundException: C:\DCIS\14-06\src\test\resources\prepurchaceOutput\paymentsuccess.txt (The system cannot find the file specified)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileReader.<init>(Unknown Source)
	at com.formsdirectinc.functionaltests.tags.AcquisitionUtils.readFile(AcquisitionUtils.java:505)
	at com.formsdirectinc.functionaltests.apps.payment.PaymentSuccess.PaymentSuccesstest(PaymentSuccess.java:110)
	at com.formsdirectinc.functionaltests.apps.payment.Payment.test(Payment.java:328)
	at com.formsdirectinc.functionaltests.apps.Step.executeNextStep(Step.java:29)
	at com.formsdirectinc.functionaltests.apps.TestEngine.start(TestEngine.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- start -->
</testsuite> <!-- com.formsdirectinc.functionaltests.apps.TestEngine -->
